### ISSUE TITLE
possible overflow bugs

### ISSUE THREAD

**Issue by harryreps** [memoryhole/libkiss#1]
https://github.com/memoryhole/libkiss/blob/cce60de8d0c1aac63b5ebb83ad819c6b70a63d30/src/libkiss.c#L68-L75

At Line 73, the frame size may be greater than the predefined size, leading to the overflow. A similar issue may happen at Line 62 and Line 68.

```
==278625==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fffa2eea6b8 at pc 0x0000005556b5 bp 0x7fffa2eea200 sp 0x7fffa2eea1f8
WRITE of size 1 at 0x7fffa2eea6b8 thread T0
    #0 0x5556b4 in kiss_parse /home/parallels/libkiss/src/libkiss.c:73:51
```

**Comment by memoryhole** [comment]
Thank you for the report. Good find.

**Comment by memoryhole** [comment]
I have a PR to address this: #2
